sudo: false
language: bash

install:
- cd ..
- "git clone https://github.com/PocketMine/PocketMine-MP.git pm && cd pm && git submodule update --init --recursive"
- wget -O - https://gist.githubusercontent.com/PEMapModder/8e3acbc287b78c66e51d/raw/a3c1a298e59932fbed85534a8d7fdade7a8dc942/compile.sh | bash -s -
- mkdir plugins

